### ISSUE TITLE
Displayed message mismatch.

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#126]
**Describe the bug**
The application shows that I have already login.

**To Reproduce**
1. Open the `jar` file.
2. Enter `logout`.

**Expected behavior**
Displayed message "You did not login into any account"

**Screenshots**
![image](https://user-images.githubusercontent.com/2564679/55452849-f5cd1d00-560b-11e9-83fd-0d7eb3b962a6.png)
![image](https://user-images.githubusercontent.com/2564679/55452853-fb2a6780-560b-11e9-8e2a-1daa6972fbdb.png)

<hr>

**Reported by:** @lycjackie
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#4]</sub>

**Comment by nicholasleeeee** [comment]
Thank you for your issue. I have fixed it :)
