### ISSUE TITLE
Example usage does not work for add command

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#127]
**Describe the bug**
As mentioned in the user guide, it gave an example of following
`add n/Tutorial 3 m/CG1112 d/21-03 t/urgent`.

However, this example results in an invalid command format.

**To Reproduce**
1. input add n/Tutorial 3 m/CG1112 d/21-03 t/urgent

**Expected behavior**
Adds a task with the name `Tutorial 3`, module code `CG1112`, 
date `21-03`, with the `tag urgent`.

**Screenshots**
![image](https://user-images.githubusercontent.com/2564679/55452938-5e1bfe80-560c-11e9-8fba-72ba04476423.png)
![image](https://user-images.githubusercontent.com/2564679/55452943-62e0b280-560c-11e9-8ec2-feeabf494a93.png)

<hr>

**Reported by:** @lycjackie
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#7]</sub>

**Comment by khairulhazril** [comment]
Fixed. Thank you!
