### ISSUE TITLE
Suggestion for display of the tasks

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#128]
For tasks which deadline is on the same day as the current system time:

Display "Task due today" instead of "Task is overdue!!!"

-- Perhaps can add time & date in order to tell user how much time left.

<hr>

**Reported by:** @yushao2
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#9]</sub>

**Comment by khairulhazril** [comment]
Thank you for the suggestion! Have made changes to reflect it.
