### ISSUE TITLE
Add function does not work as described

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#129]
**Describe the bug**
Base on user guide, example shown is to use the following command, however it does not work
`add n/Project Version 1 m/CS2113T d/11-03`

**To Reproduce**
1. enter `add n/Project Version 1 m/CS2113T d/11-03`

**Expected behavior**
I expected the task to be added in

**Screenshots**
![image](https://user-images.githubusercontent.com/46835688/55453107-23ff2c80-560d-11e9-94b8-2b008e9355c7.png)

<hr>

**Reported by:** @arhjaye
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#20]</sub>

**Comment by khairulhazril** [comment]
Fixed. Thank you!
