### ISSUE TITLE
Indicate Logout in the absence of Signing in 

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#130]
**Describe the bug**
When the application is opened and command `logout` is entered without any account signed in, it says `You have already logged out. Please Login!`
**To Reproduce**
1. Go to 'StudentBuddy.jar'
2. Run 'StudentBuddy.jar'
3. When is opened, enter command `logout`
4. Error `You have already logged out. Please Login!` is displayed

**Expected behavior**
According to the user guide, it is supposed to display `Please Login!` since I did not login into any account. 

**Screenshots**

**Additional context**
This error message is misleading. 

<hr>

**Reported by:** @truegitnovice
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#22]</sub>

**Comment by nicholasleeeee** [comment]
Thank you for your issue. This issue is repeated and has been fixed. :)
