### ISSUE TITLE
Unable to sign up multiple accounts

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#131]
**Describe the bug**
Unable to sign up multiple accounts to use.
The displayed error message mentions that 
`Account has already been created`

**To Reproduce**
1. input `signup u/1234 p/1234` 
2. input `signup u/12345 p/12345`

**Expected behavior**
Multiple accounts to be created and use to login the application.

**Screenshots**
![image](https://user-images.githubusercontent.com/2564679/55453191-7d675b80-560d-11e9-815c-099fc922fb67.png)
![image](https://user-images.githubusercontent.com/2564679/55453197-80fae280-560d-11e9-9799-04777b9e51a9.png)

However when you are login, after entering another login command. It suggests I could create another account.
![image](https://user-images.githubusercontent.com/2564679/55454573-f5845000-5612-11e9-9ef7-e1eb9fbf7487.png)

**Additional context**

If only one account could be created for the entire application, perhaps it might be
good to indicate in the `User Guide`. 

<hr>

**Reported by:** @lycjackie
**Severity:** High

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#35]</sub>

**Comment by nicholasleeeee** [comment]
Thank you for your issue. Yes only one account can be created. I have made it clearer in the user guide :)
