### ISSUE TITLE
Select function does not display on calender

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#132]
**Describe the bug**
User guide states that selecting a task will display the task on the calendar. However the calendar does not update. 

**To Reproduce**
1. Enter command `select 1`

**Expected behavior**
I expected the calender to show me the month of march where my task is 
**Screenshots**
![image](https://user-images.githubusercontent.com/46835688/55453300-d46d3080-560d-11e9-99c0-2070c654d39f.png)

<hr>

**Reported by:** @arhjaye
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#40]</sub>

**Comment by Justin-Ong** [comment]
This is intended behaviour. The task selected was not in the month displayed on the calendar, and so could not be shown as selected.
