### ISSUE TITLE
Unable to see the calendar schedule for other months other than current month

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#133]
**Please describe the problem**
After trying all the commands available and interacting with the GUI, I have been unable to access the calendars containing information of other tasks scheduled in the other months

**Describe the improvement you'd like to suggest**
Perhaps a GUI button or a simple command that will allow me to cycle between the different month's calendar would be good 

<hr>

**Reported by:** @yushao2
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#44]</sub>

**Comment by Justin-Ong** [comment]
Fair suggestion. Will work on it.

**Comment by Justin-Ong** [comment]
Functionality added in #161.
