### ISSUE TITLE
Signup indicate non existing account already created

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#134]
**Describe the bug**
When the user try to sign up again after creating account, the `signup` message indicates that the account has already.

**To Reproduce**
1. Go to 'StudentBuddy.jar'
2. Run the application
3. Enter command `signup u/nicholas p/lee`
4. See the message `Signed up: nicholas`
5. Enter another command `signup u/nicholass p/lee`
6. See the error message `Account has already been created!`

**Expected behavior**
Since the usernames `nicholas` and `nicholass` are not same, expected behaviour will the displaying the message `Signed up: nicholass` at step 6.

<hr>

**Reported by:** @truegitnovice
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#56]</sub>

**Comment by nicholasleeeee** [comment]
Thank you for your issue. This is because only one account can be created. I have made the user guide clearer. :)
