### ISSUE TITLE
add command date usage mismatch

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#135]
**Describe the bug**
The following was mention in the result box.
```
Due must be valid and should only be of the format DD-MM, where D and M number.
DD must range from 01 to 31 and MM must range from 01 to 12
```

However, when entering 31-04. The application is not accepting the format.

**To Reproduce**
1. `login` to the application.
2. `add n/Project Ver 3 m/CS2113T d/31-04 p/1 t/ungraded `

**Expected behavior**
New task added.

**Screenshots**
![image](https://user-images.githubusercontent.com/2564679/55453389-3af24e80-560e-11e9-9fb8-52c4f75e17aa.png)

**Additional context**
I assume this is because there are checks in place to ensure the date is a valid date.
Perhaps considering improving the error message instead. 

<hr>

**Reported by:** @lycjackie
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#63]</sub>

**Comment by khairulhazril** [comment]
The error message included that the date must be valid. Since 31-04 is not a valid date, it is showing the correct error message
