### ISSUE TITLE
Not able to create a new account and log in with the username and password I set 

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#136]
**Describe the bug**
Show that "Account has already been created!" when I try to create a new account that have not been created before, but I cannot login by using this account.
**To Reproduce**
1. enter "signup u/sherry p/123"
2. Show "Account has already been created!"
3. Enter "login u/sherry p/123"
4. Show "Please Login again! Command Format: [login u/USERNAME p/PASSWORD]"

**Expected behavior**
Logged in as sherry

<hr>

**Reported by:** @wupeihsuan
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#69]</sub>

**Comment by nicholasleeeee** [comment]
Thank you for your issue. I have tested your steps and I am able to signup and login as usual. You might have unknowingly created an account. Please contact the admin to have your account deleted if you forget your password.
