### ISSUE TITLE
account system

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#137]
**Please describe the problem**
is there a need for a login system? if the product is to be use own a personal computer, i would find the account system to be redundant. Logging out does not remove your tasks as well. It is still shown on the UI

<hr>

**Reported by:** @arhjaye
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#76]</sub>

**Comment by nicholasleeeee** [comment]
Thank you for your issue. Yes there is a need for a login system. This is to build protection and prevent important tasks such as (exam dates, presentation dates) from being deleted by your evil friends or hackers. There has been cases where students had their exams date corrected to a day later without them knowing, causing them to miss their exam.
