### ISSUE TITLE
Signup : Only one account can be created in the system

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#138]
**Describe the bug**
The system does not allow creation of new accounts after one has already been created in the system.

**To Reproduce**
Run the signup command after an account has already been created in the system

**Expected behavior**
Command failure: Account has already been created

*Screenshot**
<img width="431" alt="Screenshot 2019-04-03 at 12 53 02 PM" src="https://user-images.githubusercontent.com/36848472/55453698-7e00f180-560f-11e9-85a9-0da7c3683566.png">

<hr>

**Reported by:** @yushao2
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#92]</sub>

**Comment by nicholasleeeee** [comment]
Thank you for your issue. Yes, only one account can be created. I have made the user guide clearer. :)
