### ISSUE TITLE
Add function - date bug

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#139]
**Describe the bug**
While adding the task, I encountered an issue with the date formatting. My input is within the range as stated however it states that it is invalid 

**To Reproduce**
1. enter `add n/Proj Ver 2 m/CS1123T d/31-02 p/1 t/ungraded t/potato`

**Expected behavior**
I expected the task to be added
**Screenshots**
![image](https://user-images.githubusercontent.com/46835688/55453725-9d981a00-560f-11e9-9f11-3c1d5ab3bb9a.png)

<hr>

**Reported by:** @arhjaye
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#96]</sub>

**Comment by Justin-Ong** [comment]
This is intended behaviour. The input of 31st February is not a valid date, and so the task cannot be added.
