### ISSUE TITLE
Unable to add task as mentioned in UserGuide

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#140]
**Describe the bug**

**To Reproduce**
1. Run 'StudentBudyy.jar'
2. Enter command `signup u/nicholas p/lee`
3. See the message: `Signed up: nicholas`
4. Enter command `login u/nicholas p/lee`
5. See the message: `Logged in as nicholas.`
6. Enter command `add n/Tutorial 3 m/CG1112 d/21-03 t/urgent`
7. See the message `Invalid command format! 
add: Adds a task to the address book. Parameters: n/NAME m/MODULE d/DATE p/PRIORITY [t/TAG]...
Example: add n/Project Ver 1 m/CS2113T d/21-01 p/1 t/ungraded `

**Expected behavior**
According to the user guide at  [add command](https://github.com/CS2113-AY1819S2-M11-2/main/blob/master/docs/UserGuide.adoc#adding-a-task-code-add-code) example, when command `add n/Tutorial 3 m/CG1112 d/21-03 t/urgent` is entered, the application should add a task with the name Tutorial 3, module code CG1112, date 21-03, with the tag urgent. However, it is throwing the error. 

**Additional context**
Question to raise will be whether this behaviour is intended and it is the problem in the user guide.  

<hr>

**Reported by:** @truegitnovice
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#101]</sub>

**Comment by khairulhazril** [comment]
Fixed. Thank you!
