### ISSUE TITLE
Unable to have symbols in username / password for signup command

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#141]
**Describe the bug**
Unable to create an account with symbol characters in username or password (Only alphanumerics work) for the signup feature

**To Reproduce**
Run the signup command with symbols in the username or password fields

**Expected behavior**
Command fails with message: "It should not be blank!"

**Screenshots**

<img width="344" alt="Screenshot 2019-04-03 at 12 56 31 PM" src="https://user-images.githubusercontent.com/36848472/55453800-f5cf1c00-560f-11e9-8181-bf0ec07ad262.png">

<img width="315" alt="Screenshot 2019-04-03 at 12 57 27 PM" src="https://user-images.githubusercontent.com/36848472/55453822-1008fa00-5610-11e9-9a85-3157133191d4.png">

<hr>

**Reported by:** @yushao2
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#102]</sub>

**Comment by nicholasleeeee** [comment]
Yes this is indeed an issue. The bug has been fixed, now allowing special characters. Thank you, you may refer to the updated user guide for the updated information.
