### ISSUE TITLE
find name function - documentation unclear

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#142]
**Describe the bug**
user guide states that `findname CS2113 Assignment` will return: `cs2113` `assignment 2` and `homework`
does this mean it will search for this 3 terms seperately? or is this an example of the result im expected to see. 

**To Reproduce**
1. Go to 3.8 of user guide

**Screenshots**
![image](https://user-images.githubusercontent.com/46835688/55453921-6fffa080-5610-11e9-92e3-4c8a85e9b2b7.png)

<hr>

**Reported by:** @arhjaye
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#113]</sub>

**Comment by khairulhazril** [comment]
Hi, I meant that it will search both of the keywords, thus `CS2113 Homework` is listed as it has `CS2113` keyword and `Assignment 2` is listed as it has the `Assignment` keyword. Hope this helps.
