### ISSUE TITLE
Allow Tag to have space in between words 

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#143]
**Please describe the problem**
`Name` allows the space in between the words but `Tag` does not. E.g. I have to type `classParticipation` instead of `Class Participation` to add the following tag.

**Describe the improvement you'd like to suggest**
Allow the spaces between the input for the `Tag`. E.g. When type in `Class Participation`, the tag `Class Participation` is added.

<hr>

**Reported by:** @truegitnovice
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#123]</sub>

**Comment by khairulhazril** [comment]
Thank you for the suggestion but we wont have the time to implement this.
