### ISSUE TITLE
`findname` user guide example mismatch

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#146]
**Describe the bug**
As stated in the user guide. The example given for `findname` command is 
* `find CS2113 task`
* `find CS2113 Hw Tutorial`

However, the `find` command when input into the application result in 
and invalid command error.

**To Reproduce**
1. `find CS2113 task`

**Expected behavior**
Displayed all task with names containing `CS2113` or `task.

**Screenshots**
![image](https://user-images.githubusercontent.com/2564679/55454230-b1dd1680-5611-11e9-898b-ce775501c43c.png)
![image](https://user-images.githubusercontent.com/2564679/55454232-b5709d80-5611-11e9-831b-0b80086ab25e.png)

<hr>

**Reported by:** @lycjackie
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#156]</sub>

**Comment by khairulhazril** [comment]
Fixed. Thank you!
