### ISSUE TITLE
`findmodule` user guide mismatch the examples

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#147]
**Describe the bug**
According to the user guide `find CS2113T` should return all tasks containing the module code CS2113T. However, the application shows the message `Unknown command`.
**To Reproduce**
1. Run 'StudentBuddy.jar'
2. Sign in with account that is created
3. Login
4. Enter command `find CS2113T`
5. Message `Unknown command` is displayed.

**Expected behavior**
Return all tasks containing the module code CS2113T at step 5. However, the application shows the message `Unknown command`. Either update the examples on the user guide or update the command. 

<hr>

**Reported by:** @truegitnovice
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#161]</sub>

**Comment by khairulhazril** [comment]
Fixed. Thank you!
