### ISSUE TITLE
Calendar UI, task name highlight does not go away

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#148]
**Describe the bug**
Selecting a task will highlight the task name in the calendar. However the highlight does not go away even though many other commands were entered after that. Perhaps suggestion to remove the highlight when a new command is entered after select
**To Reproduce**
1. `select` any task
2.  Enter any other comments 
3. observe the highlight is still there.

**Expected behavior**
I expected the highlight in the calendar UI to be gone.

**Screenshots**
![image](https://user-images.githubusercontent.com/46835688/55454504-bce47680-5612-11e9-8ef8-5aa788836990.png)

<hr>

**Reported by:** @arhjaye
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#196]</sub>

**Comment by Justin-Ong** [comment]
Fair suggestion. Low priority, may not get done.

**Comment by Justin-Ong** [comment]
Completed in PR #166. Thanks for your suggestion.
