### ISSUE TITLE
`deletenote` user guide mismatch the examples 

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#149]
**Describe the bug**
According to the user guide `delete 1` should delete the first note from the displayed notes list in Student Buddy.. However, the application shows the message `Unknown command`.
**To Reproduce**
1. Run 'StudentBuddy.jar'
2. Sign in with account that is created
3. Login
5. Add note
4. Enter command `delete 1`
5. Message `Unknown command` is displayed.

**Expected behavior**
Deletes the first note from the displayed notes list in Student Buddy at step 5. However, the application shows the message `Unknown command`. Either update the examples on the user guide or update the command. 

<hr>

**Reported by:** @truegitnovice
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#203]</sub>

**Comment by Shengkok** [comment]
Fixed user guide (:
