### ISSUE TITLE
Instruction in the UserGuide is wrong

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#150]
**Describe the bug**
Instruction of add command is wrong

**To Reproduce**
1. enter "add n/Tutorial 3 m/CG1112 d/21-03 t/urgent" as the user guide told me to

. See error

**Expected behavior**
Should add the priority column
**Screenshots**

![螢幕快照 2019-04-03 下午1 16 17](https://user-images.githubusercontent.com/46734449/55454495-b655ff00-5612-11e9-863f-9c373e8ebb0b.png)

<hr>

**Reported by:** @wupeihsuan
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#216]</sub>

**Comment by khairulhazril** [comment]
Fixed. Thank you!
